project:
  type: website
  output-dir: _output
  resources:
    - paper.pdf
    - supplementary.pdf
  render:
    - paper.qmd
    - supplementary.qmd

# Title
title: "Title of an awesome paper"

# Authors
author:
  - name: First Author
    orcid: 0000-0000-0000-0000
    email: first.author@example.com
    affiliations:
      - ref: affiliation1
    corresponding: true
  - name: Second Author
    orcid: 0000-0000-0000-0000
    affiliations:
      - ref: affiliation2
      - ref: affiliation3
  - name: Third Author
    orcid: 0000-0000-0000-0000
    affiliations:
      - ref: affiliation1

# Author affiliations
affiliations:
  - id: affiliation1
    number: 1
    name: Affiliation 1
    city: City 1
    state: State 1
    country: Country 1
  - id: affiliation2
    number: 2
    name: Affiliation 2
    city: City 2
    state: State 2
    country: Country 2
  - id: affiliation3
    number: 3
    name: Affiliation 3
    city: City 3
    state: State 3
    country: Country 3

# Keywords
keywords:
  - keyword 1
  - keyword 2
  - keyword 3

# Abstract

bibliography: references.bib

website:
  page-navigation: true
  navbar:
    left:
      - text: "Main Text"
        file: paper.qmd
      - text: "Supplementary Material"
        file: supplementary.qmd

format:
  html:
    theme: cosmo
    default-image-extension: png
    toc: true
    filters:
      - tikz.lua
      - maintext-filter.lua
      - sitext-filter.lua
  pdf:
    pdf-engine: xelatex
    documentclass: scrartcl
    numbersections: true
    template: template.tex
    cite-method: biblatex
    default-image-extension: pdf
    include-in-header:
      - file: _preamble.tex
    biblio-style: ieee
    keep-tex: false
    filters:
      - tikz.lua
      - strip-yaml-frontmatter.lua
      - abstract-filter.lua
      - color-text-span.lua
      - maintext-filter.lua
      - sitext-refsection.lua
